# AI大模型
ruleset=💬 AI大模型,https://raw.githubusercontent.com/Howl-Star/Rules/refs/heads/Default/aimodel.list

# 影音媒体
ruleset=📺 影音媒体,[]DOMAIN,cera.awatv.de
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,1024.name
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,embyplus.org
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,28.al

# 学术科研
ruleset=📚 学术科研,https://raw.githubusercontent.com/Howl-Star/Rules/refs/heads/Default/academic.list

# 抖音与字节跳动
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list

# 广告拦截
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

# 全球直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN

# 代理服务
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

# 兜底
ruleset=🐟 漏网之鱼,[]FINAL

# 代理组
custom_proxy_group=🚀 节点选择`select`.*`[]🔗 链式代理1`[]🔗 链式代理2
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=📚 学术科研`select`[]DIRECT
custom_proxy_group=🔗 链式代理1`relay`(🇭🇰 香港 Claw|🇭🇰 香港 Bage)
custom_proxy_group=🔗 链式代理2`relay`(🇭🇰 香港 Claw|🇭🇰 香港 CNFaster)
custom_proxy_group=📺 影音媒体`select`🇺🇸.*`.*Emby.*
custom_proxy_group=💬 AI大模型`select`🇺🇸.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`.*

# 设置
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/Howl-Star/Rules/refs/heads/Default/clashdns.yml
