[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持

# 💬 AI大模型
ruleset=💬 AI大模型,[]DOMAIN-SUFFIX,x.ai
ruleset=💬 AI大模型,[]DOMAIN-SUFFIX,grok.com
ruleset=💬 AI大模型,https://raw.githubusercontent.com/Howl-Star/Rules/refs/heads/Default/chatgpt.list
ruleset=💬 AI大模型,https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/rule/openai.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN

ruleset=📚 学术科研,[]DOMAIN,webofknowledge.com
ruleset=📚 学术科研,[]DOMAIN,scopus.com
ruleset=📚 学术科研,[]DOMAIN,engineeringvillage.com
ruleset=📚 学术科研,[]DOMAIN,elsevier.com
ruleset=📚 学术科研,[]DOMAIN,sciencedirect.com
ruleset=📚 学术科研,[]DOMAIN,nature.com
ruleset=📚 学术科研,[]DOMAIN,clarivate.com
ruleset=📚 学术科研,[]DOMAIN,ams.org
ruleset=📚 学术科研,[]DOMAIN,mathjournals.org
ruleset=📚 学术科研,[]DOMAIN,projecteuclid.org
ruleset=📚 学术科研,[]DOMAIN,ems-ph.org
ruleset=📚 学术科研,[]DOMAIN,msp.org
ruleset=📚 学术科研,[]DOMAIN,siam.org
ruleset=📚 学术科研,[]DOMAIN,galegroup.com
ruleset=📚 学术科研,[]DOMAIN,aps.org
ruleset=📚 学术科研,[]DOMAIN,totalpatentone.com
ruleset=📚 学术科研,[]DOMAIN,acm.org
ruleset=📚 学术科研,[]DOMAIN,faclib.com
ruleset=📚 学术科研,[]DOMAIN,asme.org
ruleset=📚 学术科研,[]DOMAIN,emeraldinsight.com
ruleset=📚 学术科研,[]DOMAIN,oalib.com
ruleset=📚 学术科研,[]DOMAIN,nstl.gov.cn
ruleset=📚 学术科研,[]DOMAIN,tandfonline.com
ruleset=📚 学术科研,[]DOMAIN,acs.org
ruleset=📚 学术科研,[]DOMAIN,rsc.org
ruleset=📚 学术科研,[]DOMAIN,cambridge.org
ruleset=📚 学术科研,[]DOMAIN,wiley.com
ruleset=📚 学术科研,[]DOMAIN,blyun.com
ruleset=📚 学术科研,[]DOMAIN,bjzhongke.com.cn
ruleset=📚 学术科研,[]DOMAIN,xjtu.edu.cn
ruleset=📚 学术科研,[]DOMAIN,calis.edu.cn
ruleset=📚 学术科研,[]DOMAIN,proquest.com
ruleset=📚 学术科研,[]DOMAIN,metel.cn
ruleset=📚 学术科研,[]DOMAIN,springer.com
ruleset=📚 学术科研,[]DOMAIN,ieee.org
ruleset=📚 学术科研,[]DOMAIN,dyndns.com
ruleset=📚 学术科研,[]DOMAIN,science-weekly.cn
ruleset=📚 学术科研,[]DOMAIN,scival.com
ruleset=📚 学术科研,[]DOMAIN,cnki.com.cn
ruleset=📚 学术科研,[]DOMAIN,cnki.com
ruleset=📚 学术科研,[]DOMAIN,datauthor.com


# 📺 影音媒体
ruleset=🎯 全球直连,[]DOMAIN,cera.awatv.de
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,1024.name
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,embyplus.org
ruleset=📺 影音媒体,[]DOMAIN-SUFFIX,28.al

# 📱 抖音 & 字节跳动
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list

ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=📚 学术科研`select`[]🎯 全球直连
custom_proxy_group=📺 影音媒体`select`🇺🇸.*`.*Emby.*
custom_proxy_group=💬 AI大模型`select`🇺🇸.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`.*

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/Howl-Star/Rules/refs/heads/Default/clashdns.yml
